#pragma once
/*
 * TJR_gfxfont.h — GFXfont / GFXglyph struct definitions.
 *
 * Replaces the Arduino_GFX_Library.h dependency for font headers in TJR_241.
 * Font .h files generated by ttf2gfx.py include this file instead of the GFX library,
 * which is not used in the raw-framebuffer RM690B0 driver.
 *
 * Layout is identical to Adafruit GFX (compatible with Adafruit fontconvert output).
 */

#ifndef GFXFONT_H
#define GFXFONT_H

#include <stdint.h>

typedef struct {
    uint32_t bitmapOffset;  // Byte offset into the font's bitmap array
    uint8_t  width;         // Glyph bitmap width in pixels
    uint8_t  height;        // Glyph bitmap height in pixels
    uint8_t  xAdvance;      // Cursor advance after this glyph
    int8_t   xOffset;       // X pixel offset from cursor to bitmap left edge
    int8_t   yOffset;       // Y pixel offset from baseline to bitmap top edge (negative = above)
} GFXglyph;

typedef struct {
    uint8_t  *bitmap;   // Concatenated 1-bpp glyph bitmaps (big-endian, no row padding)
    GFXglyph *glyph;    // Per-glyph metrics array
    uint16_t  first;    // First ASCII code in the font
    uint16_t  last;     // Last ASCII code in the font
    uint8_t   yAdvance; // Line height (cursor advance after newline)
} GFXfont;

#endif // GFXFONT_H
