#!/usr/bin/env python3
"""
gen_digit_sprites.py — Generate a 1bpp sprite font C header for dashboard digit display.

Usage:
    python3 gen_digit_sprites.py font.ttf size_px output.h VarName

Characters rendered: 0123456789.-  (space)
Output: a C header defining a SpriteFont struct with 1bpp packed bitmaps.

The SpriteFont / SpriteGlyph types live in TJR_spritefont.h; this script
only produces the data.  Use with TJR_241's drawDigitSprite() blitter.

Why 1bpp / this approach over GFXglyph:
  GFXglyph stores xOffset/yOffset as int8_t (-128..127).  At >= ~190px even
  digit glyphs overflow that range.  Sprite approach has no size ceiling.
"""

import sys
import math
import struct
from PIL import Image, ImageFont


CHARS = '0123456789.- '   # 13 characters — all that a formatted value needs


def generate(ttf_path, size_px, out_path, var_name):
    font = ImageFont.truetype(ttf_path, size_px)

    # Line metrics — ascent is from top-of-cell to baseline (positive),
    # descent is from baseline to bottom-of-cell (positive).
    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    # Mono advance — all chars are the same width in a monospace font.
    # Use '0' as the reference character.
    x_advance = round(font.getlength('0'))

    bitmaps   = bytearray()
    glyph_meta = []   # (offset, w, h, x_offset, y_offset)

    for ch in CHARS:
        # getbbox returns (left, top, right, bottom) relative to the pen origin.
        # In Pillow convention: origin = (pen_x, baseline_y), y grows downward.
        # top is typically negative (above baseline), bottom positive (below).
        bbox = font.getbbox(ch)  # may be None for pure-whitespace chars
        if bbox is None or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            # Space or empty glyph — store zero-size entry.
            glyph_meta.append((len(bitmaps), 0, 0, 0, 0))
            continue

        left, top, right, bottom = bbox
        w = right - left
        h = bottom - top

        # x_offset: pixels from cell-left (cursor x) to bitmap left edge.
        # y_offset: pixels from cell-top (cursor y) to bitmap top edge.
        # Pillow's getbbox() for TTF fonts returns coords from the TOP of the
        # em square (not from the baseline), so top IS y_off directly.
        x_off = left
        y_off = top

        # Render the glyph into a greyscale image.
        # Draw at offset (-left, -top) so the bitmap starts at (0,0).
        img = Image.new('L', (w, h), 0)
        img.putdata(font.getmask(ch, mode='L'))

        # Pack to 1bpp: threshold at 128, MSB first, row-major.
        offset = len(bitmaps)
        bit_count = 0
        acc = 0
        for row in range(h):
            for col in range(w):
                px = img.getpixel((col, row))
                acc = (acc << 1) | (1 if px >= 128 else 0)
                bit_count += 1
                if bit_count == 8:
                    bitmaps.append(acc)
                    acc = 0
                    bit_count = 0
        if bit_count > 0:
            bitmaps.append(acc << (8 - bit_count))

        glyph_meta.append((offset, w, h, x_off, y_off))

    # ── Write C header ──────────────────────────────────────────────────────────
    lines = []
    lines.append(f'// Generated by gen_digit_sprites.py from {ttf_path} at {size_px}px')
    lines.append(f'// Share Tech Mono — OFL Licensed — https://fonts.google.com/specimen/Share+Tech+Mono')
    lines.append(f'// Characters: {repr(CHARS)}')
    lines.append(f'// lineHeight={line_height}  xAdvance={x_advance}  ascent={ascent}  descent={descent}')
    lines.append(f'#pragma once')
    lines.append(f'#include "TJR_spritefont.h"')
    lines.append(f'')

    # Bitmap array
    lines.append(f'static const uint8_t {var_name}Bitmaps[] PROGMEM = {{')
    chunk = []
    for i, b in enumerate(bitmaps):
        chunk.append(f'0x{b:02X}')
        if len(chunk) == 16 or i == len(bitmaps) - 1:
            lines.append('  ' + ', '.join(chunk) + ',')
            chunk = []
    lines.append('};')
    lines.append('')

    # Glyph array
    lines.append(f'static const SpriteGlyph {var_name}Glyphs[] PROGMEM = {{')
    lines.append(f'  // bitmapOffset, width, height, xOffset, yOffset')
    for i, (off, w, h, xo, yo) in enumerate(glyph_meta):
        ch = CHARS[i]
        disp = repr(ch)
        lines.append(f'  {{ {off:6d}, {w:3d}, {h:3d}, {xo:4d}, {yo:4d} }},  // {disp}')
    lines.append('};')
    lines.append('')

    # Char-index lookup string — same order as glyphs[]
    chars_escaped = CHARS.replace('\\', '\\\\').replace('"', '\\"')
    lines.append(f'// Character set (index into Glyphs[] = strchr(chars,c) - chars)')
    lines.append(f'static const char {var_name}Chars[] = "{chars_escaped}";')
    lines.append('')

    # Font struct
    lines.append(f'static const SpriteFont {var_name} PROGMEM = {{')
    lines.append(f'  {var_name}Bitmaps,')
    lines.append(f'  {var_name}Glyphs,')
    lines.append(f'  {var_name}Chars,')
    lines.append(f'  {len(CHARS)},          // numGlyphs')
    lines.append(f'  {x_advance},           // xAdvance (mono — same for all chars)')
    lines.append(f'  {line_height},         // lineHeight')
    lines.append(f'}};')
    lines.append('')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))

    total_bytes = len(bitmaps) + len(glyph_meta) * 12 + len(CHARS)
    print(f'Written {out_path}')
    print(f'  Bitmap:    {len(bitmaps):5d} bytes')
    print(f'  Glyphs:    {len(glyph_meta):5d} entries × 12 bytes = {len(glyph_meta)*12} bytes')
    print(f'  xAdvance:  {x_advance} px')
    print(f'  lineHeight:{line_height} px  (ascent {ascent}, descent {descent})')
    print(f'  Max 4-char string width: {x_advance * 4} px')
    print(f'  Max 5-char string width: {x_advance * 5} px')
    print(f'  Max 6-char string width: {x_advance * 6} px')


if __name__ == '__main__':
    if len(sys.argv) != 5:
        print('Usage: python3 gen_digit_sprites.py font.ttf size_px output.h VarName')
        sys.exit(1)
    generate(sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4])
